version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: click_postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: admin123
      POSTGRES_PASSWORD: dmn102030
      POSTGRES_DB: click_camisetas
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
